### ISSUE TITLE
自建数据集上使用

### ISSUE THREAD

**Issue by adii-t** [LeapLabTHU/ARC#27]
我想在自建数据集上运行这个模型，但是在切割时出现了问题：
2024-10-30 15:57:55,296 - (76.6% 3834:5002) - Filename: night_keyunzhongxin_60m_90c_frame_1350.jpg - width: 3840  - height: 2160  - Objects: 0     - Windows: 8     - Patches: 0
2024-10-30 15:57:55,299 - (76.7% 3835:5002) - Filename: night_xidongroad_100m_90c_frame_3900.jpg - width: 3840  - height: 2160  - Objects: 0     - Windows: 8     - Patches: 0
2024-10-30 15:57:55,346 - (76.7% 3836:5002) - Filename: day_jinshanshequ_60m_90c_4_frame_5550.jpg - width: 3840  - height: 2160  - Objects: 0     - Windows: 8     - Patches: 0
2024-10-30 15:57:55,356 - (76.7% 3837:5002) - Filename: night_dadengdao_60m_90c_frame_2550.jpg - width: 3840  - height: 2160  - Objects: 0     - Windows: 8     - Patches: 0
2024-10-30 15:57:55,388 - (76.7% 3838:5002) - Filename: night_city_road_100m_90c_frame_2200.jpg - width: 3840  - height: 2160  - Objects: 0     - Windows: 8     - Patches: 0
2024-10-30 15:57:55,399 - (76.7% 3839:5002) - Filename: day_zhengchenggong_60m_90c_2_frame_750.jpg - width: 3840  - height: 2160  - Objects: 0     - Windows: 8     - Patches: 0
2024-10-30 15:57:55,428 - (76.8% 3840:5002) - Filename: night_ruijingpark_100m_90c_frame_1050.jpg - width: 3840  - height: 2160  - Objects: 0     - Windows: 8     - Patches: 0
2024-10-30 15:57:55,445 - (76.8% 3841:5002) - Filename: day_ruijingpark_60m_30c_4_frame_3150.jpg - width: 3840  - height: 2160  - Objects: 0     - Windows: 8     - Patches: 0
2024-10-30 15:57:55,473 - (76.8% 3842:5002) - Filename: day_milanroad_100m_30c_frame_450.jpg - width: 3840  - height: 2160  - Objects: 0     - Windows: 8     - Patches: 0
2024-10-30 15:57:55,519 - (76.8% 3843:5002) - Filename: day _yangfanpark_100m_90c_frame_1350.jpg - width: 3840  - height: 2160  - Objects: 0     - Windows: 8     - Patches: 0
2024-10-30 15:57:55,584 - (76.8% 3844:5002) - Filename: night_yuemeihu_30m_90c_frame_3450.jpg - width: 3840  - height: 2160  - Objects: 0     - Windows: 8     - Patches: 0
2024-10-30 15:57:55,631 - (76.9% 3845:5002) - Filename: day_feitianyingbin_60m_90c_5_frame_2250.jpg - width: 3840  - height: 2160  - Objects: 0     - Windows: 8     - Patches: 0
2024-10-30 15:57:55,673 - (76.9% 3846:5002) - Filename: day_puxiyuan_60m_90c_2_frame_3000.jpg - width: 3840  - height: 2160  - Objects: 0     - Windows: 8     - Patches: 0
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/thd/anaconda3/envs/arc/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/thd/anaconda3/envs/arc/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "img_split.py", line 226, in single_split
    assert patch_infos or (filter_empty and info['ann']['bboxes'].size == 0)
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "img_split.py", line 336, in <module>
    main()
  File "img_split.py", line 314, in main
    patch_infos = pool.map(worker, zip(infos, img_dirs))
  File "/home/thd/anaconda3/envs/arc/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/thd/anaconda3/envs/arc/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AssertionError
每一份图片都没有objects

**Comment by demooooooo0303** [comment]
> 我想在自建数据集上运行这个模型，但是在切割时出现了问题： 2024-10-30 15:57:55,296 - (76.6% 3834:5002) - Filename: night_keyunzhongxin_60m_90c_frame_1350.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,299 - (76.7% 3835:5002) - Filename: night_xidongroad_100m_90c_frame_3900.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,346 - (76.7% 3836:5002) - Filename: day_jinshanshequ_60m_90c_4_frame_5550.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,356 - (76.7% 3837:5002) - Filename: night_dadengdao_60m_90c_frame_2550.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,388 - (76.7% 3838:5002) - Filename: night_city_road_100m_90c_frame_2200.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,399 - (76.7% 3839:5002) - Filename: day_zhengchenggong_60m_90c_2_frame_750.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,428 - (76.8% 3840:5002) - Filename: night_ruijingpark_100m_90c_frame_1050.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,445 - (76.8% 3841:5002) - Filename: day_ruijingpark_60m_30c_4_frame_3150.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,473 - (76.8% 3842:5002) - Filename: day_milanroad_100m_30c_frame_450.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,519 - (76.8% 3843:5002) - Filename: day _yangfanpark_100m_90c_frame_1350.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,584 - (76.8% 3844:5002) - Filename: night_yuemeihu_30m_90c_frame_3450.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,631 - (76.9% 3845:5002) - Filename: day_feitianyingbin_60m_90c_5_frame_2250.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,673 - (76.9% 3846:5002) - Filename: day_puxiyuan_60m_90c_2_frame_3000.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 multiprocessing.pool.RemoteTraceback: """ Traceback (most recent call last): File "/home/thd/anaconda3/envs/arc/lib/python3.7/multiprocessing/pool.py", line 121, in worker result = (True, func(*args, **kwds)) File "/home/thd/anaconda3/envs/arc/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar return list(map(*args)) File "img_split.py", line 226, in single_split assert patch_infos or (filter_empty and info['ann']['bboxes'].size == 0) AssertionError """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "img_split.py", line 336, in main() File "img_split.py", line 314, in main patch_infos = pool.map(worker, zip(infos, img_dirs)) File "/home/thd/anaconda3/envs/arc/lib/python3.7/multiprocessing/pool.py", line 268, in map return self._map_async(func, iterable, mapstar, chunksize).get() File "/home/thd/anaconda3/envs/arc/lib/python3.7/multiprocessing/pool.py", line 657, in get raise self._value AssertionError 每一份图片都没有objects

你用的什么格式的annotations?

**Comment by demooooooo0303** [comment]
> 我想在自建数据集上运行这个模型，但是在切割时出现了问题： 2024-10-30 15:57:55,296 - (76.6% 3834:5002) - Filename: night_keyunzhongxin_60m_90c_frame_1350.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,299 - (76.7% 3835:5002) - Filename: night_xidongroad_100m_90c_frame_3900.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,346 - (76.7% 3836:5002) - Filename: day_jinshanshequ_60m_90c_4_frame_5550.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,356 - (76.7% 3837:5002) - Filename: night_dadengdao_60m_90c_frame_2550.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,388 - (76.7% 3838:5002) - Filename: night_city_road_100m_90c_frame_2200.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,399 - (76.7% 3839:5002) - Filename: day_zhengchenggong_60m_90c_2_frame_750.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,428 - (76.8% 3840:5002) - Filename: night_ruijingpark_100m_90c_frame_1050.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,445 - (76.8% 3841:5002) - Filename: day_ruijingpark_60m_30c_4_frame_3150.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,473 - (76.8% 3842:5002) - Filename: day_milanroad_100m_30c_frame_450.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,519 - (76.8% 3843:5002) - Filename: day _yangfanpark_100m_90c_frame_1350.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,584 - (76.8% 3844:5002) - Filename: night_yuemeihu_30m_90c_frame_3450.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,631 - (76.9% 3845:5002) - Filename: day_feitianyingbin_60m_90c_5_frame_2250.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 2024-10-30 15:57:55,673 - (76.9% 3846:5002) - Filename: day_puxiyuan_60m_90c_2_frame_3000.jpg - width: 3840 - height: 2160 - Objects: 0 - Windows: 8 - Patches: 0 multiprocessing.pool.RemoteTraceback: """ Traceback (most recent call last): File "/home/thd/anaconda3/envs/arc/lib/python3.7/multiprocessing/pool.py", line 121, in worker result = (True, func(*args, **kwds)) File "/home/thd/anaconda3/envs/arc/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar return list(map(*args)) File "img_split.py", line 226, in single_split assert patch_infos or (filter_empty and info['ann']['bboxes'].size == 0) AssertionError """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "img_split.py", line 336, in main() File "img_split.py", line 314, in main patch_infos = pool.map(worker, zip(infos, img_dirs)) File "/home/thd/anaconda3/envs/arc/lib/python3.7/multiprocessing/pool.py", line 268, in map return self._map_async(func, iterable, mapstar, chunksize).get() File "/home/thd/anaconda3/envs/arc/lib/python3.7/multiprocessing/pool.py", line 657, in get raise self._value AssertionError 每一份图片都没有objects

dota格式吗？

**Comment by yifanpu001** [comment]
This repository does not involve data preprocessing. Please submit an issue under the [BboxToolkit](https://github.com/jbwang1997/BboxToolkit) repository instead.
